### ISSUE TITLE
Docker: deploy/config.yaml: no such file or directory

### ISSUE THREAD

**Issue by catalin-hritcu** [grnet/zeus#43]
I was trying to build the Zeus docker container, but I'm getting the following error:
```
zeus $ docker build .
...
Step 16/35 : ADD deploy/config.yaml /etc/puppet/hieraconf/common.yaml
ADD failed: stat /var/lib/docker/tmp/docker-builder124549296/deploy/config.yaml: no such file or directory
```
Sounds familiar to anyone?

In fact, all I'm trying to do is verify an election's proof data, so if you have any easier way to install Zeus on an Arch Linux box, please let me know.

**Comment by catalin-hritcu** [comment]
Should have mentioned from the beginning that just creating this file on the host:
```
zeus$ touch deploy/common.yaml
```
.. didn't change anything.

**Comment by catalin-hritcu** [comment]
Another thing I just tried is to just log into the partially created image and see if I can verify signatures, but that didn't work either:
```
zeus$ docker run -v /home/hritcu/Life/usr/2019-09-02-presedinte-usr:/proofs -it b26d2a43ce27 /bin/sh
zeus# cd srv/zeus_app/zeus
zeus# mkdir out
zeus# ./zeus-check-signatures /proofs/cabina-1-de-vot_proofs.txt out

1. Verify election and extract proofs of counted votes
 
loading election from '/proofs/cabina-1-de-vot_proofs.txt'
Traceback (most recent call last):
  File "./core.py", line 4948, in <module>
    retval.append(main())
  File "./core.py", line 4883, in main
    nr_parallel=nr_parallel)
  File "./core.py", line 4789, in main_verify_election
    nr_parallel=nr_parallel)
  File "./core.py", line 4232, in new_at_finished
    self = cls.new_at_decrypting(finished, teller=teller, **kw)
  File "./core.py", line 4026, in new_at_decrypting
    self = cls.new_at_mixing(decrypting, teller=teller, **kw)
  File "./core.py", line 3852, in new_at_mixing
    self = cls.new_at_voting(mixing, teller=teller, **kw)
  File "./core.py", line 3337, in new_at_voting
    self = cls.new_at_creating(teller=teller, **kw)
  File "./core.py", line 3130, in new_at_creating
    self = cls(cryptosystem, teller=teller, **kw)
  File "./core.py", line 2853, in __init__
    import zeus_sk as shuffle_module
  File "/srv/zeus_app/zeus/zeus_sk.py", line 1, in <module>
    from zeus.core import (
ImportError: No module named zeus.core
 
Press Enter to continue.
```

**Comment by catalin-hritcu** [comment]
And if I just comment out the ADD on Step 16 then things fail on Step 19:
```
Step 19/34 : RUN cd /srv/deploy && puppet apply -v zeus.pp
 ---> Running in 6db5e2139abb
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Error: Could not find data item zeus::dbname in any Hiera data file and no default supplied at /srv/deploy/zeus.pp:12 on node 6db5e2139abb.paris.inria.fr
Error: Could not find data item zeus::dbname in any Hiera data file and no default supplied at /srv/deploy/zeus.pp:12 on node 6db5e2139abb.paris.inria.fr
The command '/bin/sh -c cd /srv/deploy && puppet apply -v zeus.pp' returned a non-zero code: 1
```
This is still not enough to verify an election, since I get the same error as in the previous comment:
```
ImportError: No module named zeus.core
```

**Comment by vinilios** [comment]
Hi Catalin,

a guess for making proofs validation script to work.

```
$ cd srv/zeus_app
$ PYTHONPATH=.. python ../zeus/core.py --election <proofs-file>.txt
```

**Comment by catalin-hritcu** [comment]
Thanks a lot @vinilios, this command indeed works in the Docker container I got up to Step 19.

**Comment by catalin-hritcu** [comment]
The important part of the fix is actually just this:
```
export PYTHONPATH=/srv/zeus_app
```
For verifying in the end I'm still using the more comprehensive `zeus-check-signatures`:
```
./zeus-check-signatures -p 8 /proofs/cabina-2-de-vot_proofs.txt /proofs/signatures
```

**Comment by vinilios** [comment]
I've just tried building the Docker image from the master branch and it seems to work. Make sure the config file exists prior to building the image.

```
$ cp deploy/config.yaml.example deploy/config.yaml
```

I'm closing this for now.

**Comment by catalin-hritcu** [comment]
I can confirm that this copy is all that's needed to make everything work. Thanks a lot.
